// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/blog/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Blog service

func NewBlogEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Blog service

type BlogService interface {
	Category(ctx context.Context, in *CategoryIndexRequest, opts ...client.CallOption) (*CategoryIndexResponse, error)
	Article(ctx context.Context, in *ArticleRequest, opts ...client.CallOption) (*ArticleResponse, error)
}

type blogService struct {
	c    client.Client
	name string
}

func NewBlogService(name string, c client.Client) BlogService {
	return &blogService{
		c:    c,
		name: name,
	}
}

func (c *blogService) Category(ctx context.Context, in *CategoryIndexRequest, opts ...client.CallOption) (*CategoryIndexResponse, error) {
	req := c.c.NewRequest(c.name, "Blog.Category", in)
	out := new(CategoryIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogService) Article(ctx context.Context, in *ArticleRequest, opts ...client.CallOption) (*ArticleResponse, error) {
	req := c.c.NewRequest(c.name, "Blog.Article", in)
	out := new(ArticleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blog service

type BlogHandler interface {
	Category(context.Context, *CategoryIndexRequest, *CategoryIndexResponse) error
	Article(context.Context, *ArticleRequest, *ArticleResponse) error
}

func RegisterBlogHandler(s server.Server, hdlr BlogHandler, opts ...server.HandlerOption) error {
	type blog interface {
		Category(ctx context.Context, in *CategoryIndexRequest, out *CategoryIndexResponse) error
		Article(ctx context.Context, in *ArticleRequest, out *ArticleResponse) error
	}
	type Blog struct {
		blog
	}
	h := &blogHandler{hdlr}
	return s.Handle(s.NewHandler(&Blog{h}, opts...))
}

type blogHandler struct {
	BlogHandler
}

func (h *blogHandler) Category(ctx context.Context, in *CategoryIndexRequest, out *CategoryIndexResponse) error {
	return h.BlogHandler.Category(ctx, in, out)
}

func (h *blogHandler) Article(ctx context.Context, in *ArticleRequest, out *ArticleResponse) error {
	return h.BlogHandler.Article(ctx, in, out)
}
